### ISSUE TITLE
Lab 1 - Step 3

### ISSUE THREAD

**Issue by mmonakho** [Watts-College/cpp-527-spr-2022#10]
I was wondering why the code in Step 3 starts with "game". Where is it coming from? Step 1 had "a.game"...

open_goat_door <- function( **game**, a.pick )

**Comment by Dselby86** [comment]
open_goat_door <- function( *game*, a.pick )

Is declaring a function named open_goat_door

That function will be looking for two arguments game and a.pick

When you use write the function you can use game and a.pick as variables in
the function. But they exist for that function only.

So game is a separate variable than a.game.

I hope this helps

**Comment by mmonakho** [comment]
It does, thank you!

**Comment by mmonakho** [comment]
Why didn't we put a.game or a.pick in brackets in Steps 1-2?

**Comment by trioptre** [comment]
@Dselby86 

Can you clarify the sentence "That function will be looking for two arguments game and a.pick"?

Also, your sentence "When you use write the function you can use game and a.pick as variables in
the function" - what does this mean?

Thanks,
Dave

**Comment by Dselby86** [comment]
Hi Dave,

When you create a function you declare the arguments that function is
supposed to accept inside of the ().  in this case "function(game,
a.pick)".  Then the function can use the values provided for the game and
a.pick inside the function.

However, when you call the function you must provide values for game and
a.pick.

So

test <- function(game, a.pick)


test(5, 6)

will assign 5 for game and 6 for a.pick.

You can also manually set the value of the arguments: test (a.pick = 6,
game = 5)

But if you call the function without one of the required arguments it will
return an error

test(5)  # this won't work

Hope this helps.

**Comment by Dselby86** [comment]
@mmonakho


That is just the way the code is written.  You can have variables take on any name, but it is best to use something consistent that you and someone else can follow

**Comment by mmonakho** [comment]
Thank you!
