### ISSUE TITLE
Typos and misspellings in course materials

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#11]
Hello -

I've noticed numerous typos, misspellings, and nonsensical sentences in the course materials. Is there a feedback mechanism to get these corrected?

Example: (From [Practice Problem Warmup](https://watts-college.github.io/cpp-527-spr-2022/schedule/#practice-problem-warmup))
_"Non-obvious bugs can EASILY work there way into your code. Once you identify the problem always seems obvious in retrospect"_

Thanks,
Dave

**Comment by trioptre** [comment]
@Dselby86 - why was this issue closed?

**Comment by Dselby86** [comment]
Because while there is a word missing, I have no ability to change the
underlying digital textbook that that text comes from.
