### ISSUE TITLE
Difference between Lab Sessions and Review Sessions?

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#13]
Hi @Dselby86 

What is the difference between the [Lab Sessions (Thursdays at 7pm AZ time)](https://watts-college.github.io/cpp-527-spr-2022/) and [Review Sessions (Mondays at 12pm AZ time)](https://watts-college.github.io/cpp-527-spr-2022/review/)?

Thanks,
Dave

**Comment by Dselby86** [comment]
Review sessions and Lab sessions are the same. They are Thursdays at 7:30
pm.

**Comment by trioptre** [comment]
Thank you, @Dselby86 ; since they were called different things and were on different days, I assumed they were distinct from each other. Thank you also for correcting the syllabus regarding this issue.
