### ISSUE TITLE
Testing for Statistical Significance 

### ISSUE THREAD

**Issue by dholford** [Watts-College/cpp-527-spr-2022#14]
For Lab 2 Part 2 we are asked about the "dominant" strategy. In the scenario where there are 5 goats and 2 cars my table looked like this:
                              outcome
strategy       LOSE           WIN
  stay            0.72             0.28
  switch        0.66             0.34

I then starting thinking, well, ultimately I'd want to know if the difference in win % between staying and switching was actually statistically significant. I have to admit, I don't remember exactly how to figure that out. I started by looking for ways to do this in R, and was playing around with t.test() I realized, though, that in running 10,000 games we still ended with 1 mean. To actually run a t.test, we would want a distribution of means. So we would need to run another loop, or connect another loop to the current functions to calculate the mean win % for stay and switch for a given scenario and do that over and over so we ended up with enough means to run a t-test. 

I'm I thinking about that correctly?

**Comment by Dselby86** [comment]
Hi Dylan

You can also think of the t test as having a mean of your stay/switch win
percent and a sample size of 1000

**Comment by dholford** [comment]
Got it, I think I can figure it out from there.

Thanks!
