### ISSUE TITLE
Lab 4 Part 2

### ISSUE THREAD

**Issue by mmonakho** [Watts-College/cpp-527-spr-2022#25]
**When running this chunk of code...**

tokens <- tokens( corp, what="word", remove_punct=TRUE )

**...getting this error:**

Error: tokens() only works on character, corpus, list, tokens objects.

**Comment by mmonakho** [comment]
**Which doesn't make sense because I checked the type of _corp_ variable...**

 typeof(corp)
[1] "character"

**Comment by Dselby86** [comment]
Can you post the code that declares the Corp object

**Comment by mmonakho** [comment]
**I copy-pasted it at from the lab instructions:**
dat$mission <- tolower( dat$mission )
set.seed(1986)
dat.sample <- dat[ sample( 1:50000, size=1000 ) , ]
corp <- corpus( dat.sample,  text_field="mission" )
corp <- ?corpus_trim(corp, what="sentences", min_token=3)

**Actually, this part doesn't work either:**
corp <- corpus_trim(corp, what="sentences", min_token=3)

**Gives this error:**
Error in corpus_trim(corp, what = "sentences", min_token = 3) : 
  could not find function "corpus_trim"

**Comment by Dselby86** [comment]
make sure you have all of the packages loaded.

library( dplyr )
library( pander )
library( quanteda )
library( quanteda.textmodels )
library( quanteda.textstats )
library( quanteda.textplots )

Also the line you just linked should be:

corpus_trim( corp, what="sentences", min_*n*token=3 )


For your first question carefully follow your corp object through the code
until it gets to the tokens line.  The command you posted is correct, and
it should work.  It looks like somewhere you either overwrote your corp
object, or something went wrong with loading your packages

**Comment by mmonakho** [comment]
That missing n was the problem... thank you very much for your help!
