### ISSUE TITLE
Syllabus "Get Help" link broken

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#3]
Hello - 

Section F of the [Syllabus ](https://watts-college.github.io/cpp-527-spr-2022/) is not working:

"Please post lab questions on the [Get Help](https://watts-college.github.io/help/) page on this site, schedule individual office hours using the Calendly link provided above, and email the instructor directly instead of using the Canvas system."

The "Get Help" link above takes me to a 404: Page not found error page.

Can you get the link in the syllabus updated/corrected/working again?

**Comment by Dselby86** [comment]
I got it updated, it should bring everyone to this board now

Thank you.

**Comment by trioptre** [comment]
@Dselby86 - 

Did you test to verify the link was working before closing this issue?

I'm still getting a 404 not found error when I use the [Get Help](https://watts-college.github.io/help/) link in [Section F of the Syllabus ](https://watts-college.github.io/cpp-527-spr-2022/), and the link has not changes as far as I can tell.

Thank you,
Dave

**Comment by Dselby86** [comment]
It should work now.

I had checked the link at the top of the page not the one deep in the
syllabus
