### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-527-spr-2022#33]
In the instructions for the final project it says:

"Before you go on to next steps, download these three files do your local working directory. Open batch.R in a regular R console and try running the reports to create the HTML files."

When I run the batch.R file, I get the following error:

Quitting from lines 15-47 (salary-report.rmd) 
Error in eval(expr, envir, enclos) : object 'params' not found

When I look at line 15, it is a call to the url that is defined in the `render()` function. 

My question is whether these files should work as they are posted on the instructions page. Thanks!

**Comment by Dselby86** [comment]
HI Jacob.

Are the files saved in your working directory? Did you change the working
directory to be the same location as your file?

**Comment by jacobtnyoung** [comment]
I did. The problem is with the `URL <- params$url` command in the .Rmd file. Although `params` is identified in the batch.R file, it doesn't seem to be creating the object.

**Comment by Dselby86** [comment]
Let me do some digging and I'll get back to you

**Comment by jacobtnyoung** [comment]
Thanks.

**Comment by jacobtnyoung** [comment]
I figured it out. I didn't have the YAML header set up.

```
params:
  url:
    value: x   
```

This fixed it!
