### ISSUE TITLE
"No Title" Announcement 1/11

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#4]
Hello - 

The [Yellowdig link](https://yellowdig.app/share/heavy-dingo-89 ) provided in the "No Title" announcement takes me to a Yellowdig login page, but I'm not sure which credentials to use.

Can you advise how to access Yellowdig using the link provided?

Thanks!

**Comment by Dselby86** [comment]
Try this link:

https://canvas.asu.edu/courses/108491/assignments/2839806

Yellowdig seems to sometimes accept our students but other times it will not

**Comment by trioptre** [comment]
Thank you, @Dselby86  - can you post an updated announcement with the proper link via Canvas (with an appropriately descriptive subject line)? I haven't been able to access Yellowdig until today, unfortunately.
