### ISSUE TITLE
Post Practice Problems on Yellowdig (Due Dates)

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#5]
Hello - 

Can you explain what "Post Practice Problems on YellowDig" means on the [Syllabus Schedule](https://watts-college.github.io/cpp-527-spr-2022/schedule/)?

Do I need to post a practice problem on the due date(s)?

Since I cannot access Yellowdig (see https://github.com/Watts-College/cpp-527-spr-2022/issues/4#issue-1104830194) and the Yellowdig link provided for the [Practice Problem Warmup](https://canvas.asu.edu/courses/99223/assignments/2552420) takes me to a "Not Authorized" error page, with this first Yellowdig due date be adjusted?

Thanks!

**Comment by trioptre** [comment]
@Dselby86 - why was this issue closed?

**Comment by Dselby86** [comment]
Dave you make a lot of comments on the git hub page and I thought I had
addressed it. Ie your link to your own comment for this comment

I need you to work the practice problems each week and post your results
and discussion on Yellow dig.
