### ISSUE TITLE
Practice Problem Warmup Yellowdig link - "Access Denied"

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#6]
Hello -

The [Yellowdig ](https://canvas.asu.edu/courses/99223/assignments/2552420)link under Practice Problem Warmup section on the following page give me an "Access Denied" error.

Can you advise?

**Comment by Dselby86** [comment]
Try This Link:


https://canvas.asu.edu/courses/108491/assignments/2839806

YellowDig is acting strange
