### ISSUE TITLE
Review Session 1 1/13 Cancelled; Due Date Adjustment?

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-527-spr-2022#8]
Hello @Dselby86 - 

Since the first review session was cancelled, and the due date son the SYllabus were incorrect until recently,  will any due dates be adjusted?

Thanks,
Dave

**Comment by Dselby86** [comment]
Hi Dave,

As you can imagine with COVID we all need to be a little flexible. I'm not intending to move any of the Due Dates. If you have particular needs send me an email.

David Selby
